### ISSUE TITLE
Panel crashes on executing a custom command plugin action or command with only white spaces

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-panel#1965]
Maybe fixed by https://github.com/lxqt/lxqt-panel/pull/1964

##### Steps to Reproduce (for bugs)

1. Insert some white spaces as "click" action in a custom command plugin
2. click it
3. Panel restarts

```

#0  0x00007fd732cac83c in  () at /usr/lib/libc.so.6
#1  0x00007fd732c5c668 in raise () at /usr/lib/libc.so.6
#2  0x00007fd732c444b8 in abort () at /usr/lib/libc.so.6
#3  0x00007fd7332a00c2 in qt_assert(char const*, char const*, int) () at /usr/lib/libQt5Core.so.5
#4  0x00007fd7332a0120 in qt_assert_x(char const*, char const*, char const*, int) () at /usr/lib/libQt5Core.so.5
#5  0x00007fd715dbd192 in QList<QString>::first() (this=0x7ffe66755aa8) at /usr/include/qt/QtCore/qlist.h:361
#6  0x00007fd715dbcc0e in QList<QString>::takeFirst() (this=0x7ffe66755aa8) at /usr/include/qt/QtCore/qlist.h:603
#7  0x00007fd715dbb724 in LXQtCustomCommand::runDetached(QString) (this=0x555d069709a0, command=...)
    at /home/stef/git/lxqt/lxqt-panel/plugin-customcommand/lxqtcustomcommand.cpp:258
#8  0x00007fd715dbae6b in LXQtCustomCommand::handleClick() (this=0x555d069709a0)
    at /home/stef/git/lxqt/lxqt-panel/plugin-customcommand/lxqtcustomcommand.cpp:171
#9  0x00007fd715dbdd66 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (LXQtCustomCommand::*)()>::call(void (LXQtCustomCommand::*)(), LXQtCustomCommand*, void**)                                                                                                                               
    (f=(void (LXQtCustomCommand::*)(LXQtCustomCommand * const)) 0x7fd715dbae0a <LXQtCustomCommand::handleClick()>, o=0x555d069709a0, arg=0x7ffe66755cb0)
    at /usr/include/qt/QtCore/qobjectdefs_impl.h:152
#10 0x00007fd715dbd920 in QtPrivate::FunctionPointer<void (LXQtCustomCommand::*)()>::call<QtPrivate::List<>, void>(void (LXQtCustomCommand::*)(), LXQtCustomCommand*, void**)                                                                                                                                                     
    (f=(void (LXQtCustomCommand::*)(LXQtCustomCommand * const)) 0x7fd715dbae0a <LXQtCustomCommand::handleClick()>, o=0x555d069709a0, arg=0x7ffe66755cb0)
    at /usr/include/qt/QtCore/qobjectdefs_impl.h:185
#11 0x00007fd715dbd369 in QtPrivate::QSlotObject<void (LXQtCustomCommand::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x555d06dbe860, r=0x555d069709a0, a=0x7ffe66755cb0, ret=0x0) at /usr/include/qt/QtCore/qobjectdefs_impl.h:418                           
#12 0x00007fd7334d1097 in  () at /usr/lib/libQt5Core.so.5
#13 0x00007fd73425c687 in QAbstractButton::clicked(bool) () at /usr/lib/libQt5Widgets.so.5
#14 0x00007fd73425ef3a in  () at /usr/lib/libQt5Widgets.so.5
#15 0x00007fd73426043c in  () at /usr/lib/libQt5Widgets.so.5
#16 0x00007fd7342605e0 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/libQt5Widgets.so.5
#17 0x00007fd73435376f in QToolButton::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/libQt5Widgets.so.5
#18 0x00007fd7341af1a1 in QWidget::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#19 0x00007fd7341788ff in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#20 0x00007fd73417ddaf in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#21 0x00007fd73349c168 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#22 0x00007fd73417c0ea in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) ()
    at /usr/lib/libQt5Widgets.so.5
#23 0x00007fd7341cceb5 in  () at /usr/lib/libQt5Widgets.so.5
#24 0x00007fd7341cec07 in  () at /usr/lib/libQt5Widgets.so.5
#25 0x00007fd7341788ff in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#26 0x00007fd73349c168 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#27 0x00007fd73394196c in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/libQt5Gui.so.5
#28 0x00007fd73392a6f5 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Gui.so.5
#29 0x00007fd72fb5ece5 in  () at /usr/lib/libQt5WaylandClient.so.5
#30 0x00007fd734aaaf69 in  () at /usr/lib/libglib-2.0.so.0
#31 0x00007fd734b09367 in  () at /usr/lib/libglib-2.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#32 0x00007fd734aa9162 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#33 0x00007fd7334eaf7c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#34 0x00007fd73349ae74 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#35 0x00007fd73349c313 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#36 0x0000555d040b6169 in main(int, char**) (argc=3, argv=0x7ffe66756b08) at /home/stef/git/lxqt/lxqt-panel/panel/main.cpp:42
```

* LXQt Version: 1.4  and older

**Comment by tsujan** [comment]
Fixed in https://github.com/lxqt/lxqt-panel/commit/bd637abafc9e8e9c7727a89e5d86e0f07f213c23
